### ISSUE TITLE
Improve Redirect Configuration meta box field arrangement

### ISSUE THREAD

**Issue by raamdev** [raamdev/wp-redirects#13]
The Redirect Configuration meta box currently has the (optional) **Redirection Status** field at the top. That doesn't make since from a UX-perspective. Since that field is optional, it will most likely rarely get used. The second field (**Redirection URL**) should be the first field, and the **Redirection Status** field should be the last field. 

![2014-09-11_23-06-05](https://cloud.githubusercontent.com/assets/53005/4244908/19abddae-3a2a-11e4-9606-bd030e5226b3.png)

---

In fact, perhaps each of those fields (Redirection URL, Additional Redirections From, and Redirection Status) should be their own Meta Boxes. That way, a site owner can show/hide the ones they use the most. Separating them into separate Meta Boxes would, in my opinion be fine, since the entire page itself is dedicated to the Redirect Configuration. Also, that existing Redirect Configuration meta box feels _very_ crowded.

@jaswsinc Thoughts?

**Comment by jaswrks** [comment]
I agree on all points!

 Another thing that bugs me about the current layout, is that the tab order seems really out of whack (for whatever reason). I type the title of the Redirect into the field provided, and then I tab down into something other than what I expect. Not sure if we can do anything about this, but if so that would help too I think. It should be quicker and easier to create a redirection.

**Comment by raamdev** [comment]
The Redirect configuration options have been separated into separate Meta Boxes. I also added lots of inline documentation to help novice site owners.

![2014-09-13_20-52-59](https://cloud.githubusercontent.com/assets/53005/4262561/8e04918e-3ba9-11e4-89f0-f607748e5abb.png)
![2014-09-13_20-53-13](https://cloud.githubusercontent.com/assets/53005/4262562/8fba543c-3ba9-11e4-8f10-c7bcac7cafd4.png)

**Comment by raamdev** [comment]
> Another thing that bugs me about the current layout, is that the tab order seems really out of whack (for whatever reason). I type the title of the Redirect into the field provided, and then I tab down into something other than what I expect. Not sure if we can do anything about this, but if so that would help too I think. It should be quicker and easier to create a redirection.

I looked into this and unfortunately there's no easy fix. See https://www.google.com/search?q=wordpress+metabox+tabindex

**Comment by raamdev** [comment]
@jaswsinc Any feedback here? If it looks good to you, I'll go ahead and merge this. :)

**Comment by jaswrks** [comment]
Wow, awesome!!

> I looked into this and unfortunately there's no easy fix. See https://www.google.com/search?q=wordpress+metabox+tabindex

Gotcha :-)

> @jaswsinc Any feedback here? If it looks good to you, I'll go ahead and merge this. :)

I'm sure it's fine. I am going to pull this branch and run tests in just a moment. I will report back shortly.

**Comment by jaswrks** [comment]
Tested... Yep, looks like pure awesomeness to me! :-) :thumbsup:

**Comment by raamdev** [comment]
Great! Thanks @jaswsinc :)

**Comment by raamdev** [comment]
Next release changelog: 
- **Enhancement**: Overhauled the New/Edit Redirect screen. Sections are now modular meta boxes that can be hidden/shown using the Screen Options panel. Lots of inline documentation was also added to help clarify each option. See [#13](https://github.com/websharks/wp-redirects/issues/13).
