### ISSUE TITLE
Stats on Right by Default, Maybe?

### ISSUE THREAD

**Issue by jaswrks** [raamdev/wp-redirects#17]
It would be cool if the stats showed up on the right side by default I think. No biggy, I can drag them over there, but it seems a little more convenient that way. I think it should remain optional like you have it already, just maybe it could start out on the right side.

![2014-10-09_16-12-48](https://cloud.githubusercontent.com/assets/1563559/4586175/4a961e86-5012-11e4-993b-0182815ff37b.png)

**Comment by raamdev** [comment]
Great point!

**Comment by raamdev** [comment]
Fixed! The Redirect Statistics Meta Box now shows up on the bottom side by default:

![2014-10-09_20-22-18](https://cloud.githubusercontent.com/assets/53005/4586246/8afc71fe-5013-11e4-9579-e3ba85216931.png)

This will go out with the next release.

**Comment by raamdev** [comment]
Next release changelog:
- **Enhancement**: Show the Redirection Statistics meta box on the side by default. See [#17](https://github.com/websharks/wp-redirects/issues/17).

**Comment by jaswrks** [comment]
Cool! Thanks :-)
