### ISSUE TITLE
did the plugin redirect my old products affiliate url? 

### ISSUE THREAD

**Issue by stathisk9** [raamdev/wp-redirects#23]
Hi,

did the plugin redirect my old products affiliate url?

more specific, i imported affiliate products from a network, but now the
eshop that advertised in the network remove the connection from it and i
have thousand products with dead affiliate links,

the affiliate links starting with the same base and the eshop's ID,
is it possible to cloak and redirect all of them?

example based affiliate url:
http: // go. thenetwork. se/z/shopID:399-0/my-ID:CD966/?lnkurl= theproducturl

to avoid delete those products because of Google index, i like to
redirect the "Buy Now" button,

it is important for me because i have the same issue in all of my
affiliate sites,

Thanks,
Stathis

**Comment by raamdev** [comment]
So you're trying to redirect FROM this URL:

http://go.thenetwork. se/z/shopID:399-0/my-ID:CD966/?lnkurl= theproducturl

TO what URL?
