### ISSUE TITLE
Feature Request: Hit Counter

### ISSUE THREAD

**Issue by raamdev** [raamdev/wp-redirects#4]
It would be really great if WP-Redirects maintained a record of each time a link was redirected and then displayed that data.

Here's how the [Redirection plugin](http://wordpress.org/plugins/redirection/) (1.6M downloads) does it:

![screen shot 2014-05-28 at 11 04 57 am](https://cloud.githubusercontent.com/assets/53005/3106170/b0f1a63a-e679-11e3-823e-40fb17c2c806.png)

**Comment by jaswrks** [comment]
Love this idea! Thanks.

**Comment by raamdev** [comment]
Closed by PR #8.

**Comment by raamdev** [comment]
Next release changelog:
- **New Feature**: Hit counter. WP Redirects will now keep track of how many times a redirect has been used. There is a new, sortable Hits column in the main Redirects list that allows you to sort your redirects by the number of hits.

**Comment by raamdev** [comment]
Next release changelog:
- **New Feature**: Last Access Time. WP Redirects will now keep track of the date and time a redirect was last used. There is a new, sortable Last Access column in the main Redirects list that allows you to sort your redirect by the last access time. See [#4](https://github.com/websharks/wp-redirects/issues/4).
